name: Backend-CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repository Checkout
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set application.yml
      run: |
        mkdir -p ./src/main/resources
        touch ./src/main/resources/application.yml
        echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml

    - name: Set application-test.yml
      run: |
        mkdir -p ./src/test/resources
        touch ./src/test/resources/application-test.yml
        echo "${{ secrets.APPLICATION_TEST }}" > ./src/test/resources/application-test.yml

    - name: Check application-test.yml content
      run: cat ./src/test/resources/application-test.yml

    - name: Grant execute permission for Gradle
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew test

