name: Backend-CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Repository Checkout
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set application.yml
      run: |
        mkdir -p ./src/main/resources
        cd ./src/main/resources
        touch ./application.yml
        echo "${{ secrets.APPLICATION }}" > ./application.yml

    - name: Set application-test.yml
      run: |
        mkdir -p ./src/test/resources
        cd ./src/test/resources
        touch ./application-test.yml
        echo "${{ secrets.APPLICATION_TEST }}" > ./application-test.yml

    - name: Check application-test.yml content
      run: cat ./src/test/resources/application-test.yml

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Grant execute permission for Gradle
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew build

