name: Backend-CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
    - name: Repository Checkout
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set application.yml
      run: |
        mkdir -p ./src/main/resources
        touch ./src/main/resources/application.yml
        echo "${{ secrets.APPLICATION }}" | base64 --decode > ./src/main/resources/application.yml

    - name: Set application-test.yml, application-mongo.yml
      run: |
        mkdir -p ./src/test/resources
        touch ./src/test/resources/application-h2.yml
        touch ./src/test/resources/application-mongo.yml
        echo "${{ secrets.APPLICATION_H2 }}" | base64 --decode > ./src/test/resources/application-h2.yml
        echo "${{ secrets.APPLICATION_MONGO }}" | base64 --decode > ./src/test/resources/application-mongo.yml
        

    - name: Grant execute permission for Gradle
      run: chmod +x gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew test

